sudo: false
language: python
python:
  - "3.8"

install:
  # See: https://tabatkins.github.io/bikeshed/#travis-ci
  - pip3 install bikeshed
  - bikeshed update

script:
  - bash "./deploy.sh"

env:
  global:
  - ENCRYPTION_LABEL: "b6936e521be2"
  - COMMIT_AUTHOR_EMAIL: "plh+deploy@w3.org"
